title: Psykokat
description: >
  We, the psychotic cats have been watching you through the internet, soon we will be coming for you. Beware. 
baseurl: ""
url: "http://Psychopaz.github.io"
paginate:	5 # The number of posts to show per page on your homepage
name: "Kitty"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
