title: Blog Sonia
description: >
  Le blog de sonia la rigolote
baseurl: ""
url: "http://Psychopaz.github.io"
paginate:	5 # The number of posts to show per page on your homepage
name: "Sonia"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
